FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
RUN curl -sL https://deb.nodesource.com/setup_24.x | bash - && apt install -y nodejs && rm -rf /var/lib/apt/lists/*
WORKDIR /app/src
COPY src/ .
RUN dotnet restore BeatSaverMatcher.Web/BeatSaverMatcher.Web.csproj
RUN dotnet publish -c Release BeatSaverMatcher.Web/BeatSaverMatcher.Web.csproj -o /app/build


FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
RUN apk add --no-cache \
    icu-data-full \
    icu-libs

WORKDIR /app
COPY --from=build /app/build/ ./
ENTRYPOINT ["dotnet", "BeatSaverMatcher.Web.dll"]