FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app/src
COPY src/ .
RUN dotnet restore BeatSaverMatcher.Crawler/BeatSaverMatcher.Crawler.csproj
RUN dotnet publish -c Release BeatSaverMatcher.Crawler/BeatSaverMatcher.Crawler.csproj -o /app/build

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build /app/build/ ./
ENTRYPOINT ["dotnet", "BeatSaverMatcher.Crawler.dll"]